import { saveAssignmentAction, updateAssignmentSubmissionAction } from "@/actions/admin";
import { Button } from "@/components/ui/button";
import { AdminPageHeader, AdminSection, AdminTable, Field, HiddenId, Select, StatusBadge, Textarea } from "@/components/admin/admin-resource-page";
import { firstAdminRelation, getAdminAssignments, getAdminCourses } from "@/lib/admin-dashboard";

export default async function AdminAssignmentsPage() {
  const [{ assignments, submissions }, courses] = await Promise.all([getAdminAssignments(), getAdminCourses()]);
  return <div><AdminPageHeader eyebrow="Learning" title="Assignments" description="Create assignments and review student submissions." /><div className="mt-8 grid gap-6"><AdminSection title="Create assignment"><form action={saveAssignmentAction} className="grid gap-4 md:grid-cols-2"><Select label="Course" name="courseId" required={false} options={[{ label: "No course", value: "" }, ...courses.map((course) => ({ label: course.title, value: course.id }))]} /><Field label="Title" name="title" /><Field label="Due at" name="dueAt" type="datetime-local" /><Select label="Status" name="status" options={["draft", "published", "archived"]} /><div className="md:col-span-2"><Textarea label="Description" name="description" /></div><Button type="submit" variant="accent">Create assignment</Button></form></AdminSection><AdminSection title="Assignments"><AdminTable rows={assignments} emptyLabel="No assignments found." columns={[{ header: "Assignment", cell: (row) => <div><p className="font-bold text-white">{row.title}</p><p>{firstAdminRelation(row.courses)?.title ?? row.course_id ?? "General"}</p></div> }, { header: "Due", cell: (row) => row.due_at ? new Date(row.due_at).toLocaleString("en-BD") : "-" }, { header: "Status", cell: (row) => <StatusBadge value={row.status} /> }]} /></AdminSection><AdminSection title="Submissions"><AdminTable rows={submissions} emptyLabel="No submissions found." columns={[{ header: "Submission", cell: (row) => <div><p className="font-bold text-white">{firstAdminRelation(row.assignments)?.title ?? row.assignment_id}</p><p>{firstAdminRelation(row.profiles)?.email ?? row.user_id}</p></div> }, { header: "Status", cell: (row) => <StatusBadge value={row.status} /> }, { header: "Grade", cell: (row) => row.grade ?? "-" }, { header: "Action", cell: (row) => <form action={updateAssignmentSubmissionAction} className="grid gap-2"><HiddenId id={row.id} /><Select label="Status" name="status" options={["submitted", "reviewed", "approved", "rejected"]} /><Field label="Grade" name="grade" type="number" /><Button type="submit" size="sm" variant="accent">Review</Button></form> }]} /></AdminSection></div></div>;
}
