import { deleteProductAction, saveProductAction } from "@/actions/admin";
import { Button } from "@/components/ui/button";
import { ActionButton, AdminSection, AdminTable, Field, HiddenId, Select, StatusBadge, Textarea } from "@/components/admin/admin-resource-page";
import type { AdminProductRow } from "@/lib/admin-dashboard";
import { formatBdt } from "@/lib/admin-dashboard";

export function ProductManager({ products }: { products: AdminProductRow[] }) {
  return <div className="grid gap-6"><AdminSection title="Create product" description="Digital product records can later be attached to paid orders and protected downloads."><form action={saveProductAction} className="grid gap-4 md:grid-cols-2"><Field label="Title" name="title" /><Field label="Slug" name="slug" /><Field label="Category" name="category" /><Field label="Price BDT" name="priceBdt" type="number" defaultValue="0" /><Select label="Access type" name="accessType" options={["download", "course_bundle", "external"]} /><Select label="Status" name="status" options={["draft", "published", "archived"]} /><Field label="File path" name="filePath" /><div className="md:col-span-2"><Textarea label="Description" name="description" /></div><div className="md:col-span-2"><ActionButton>Create product</ActionButton></div></form></AdminSection><AdminSection title="Products"><AdminTable rows={products} emptyLabel="No products yet." columns={[{ header: "Product", cell: (row) => <div><p className="font-bold text-white">{row.title}</p><p>{row.slug}</p></div> }, { header: "Category", cell: (row) => row.category ?? "-" }, { header: "Price", cell: (row) => formatBdt(row.price_bdt) }, { header: "Access", cell: (row) => row.access_type ?? "download" }, { header: "Status", cell: (row) => <StatusBadge value={row.status} /> }, { header: "Action", cell: (row) => <form action={deleteProductAction}><HiddenId id={row.id} /><Button type="submit" variant="ghost" size="sm">Delete</Button></form> }]} /></AdminSection></div>;
}
