import { updateOrderAccessAction } from "@/actions/admin";
import { ActionButton, AdminPageHeader, AdminSection, AdminTable, HiddenId, Select, StatusBadge } from "@/components/admin/admin-resource-page";
import { firstAdminRelation, formatBdt, getAdminOrders } from "@/lib/admin-dashboard";
import { formatAccessType } from "@/lib/public-data";

export default async function AdminOrdersPage() {
  const orders = await getAdminOrders();
  return <div><AdminPageHeader eyebrow="Shop" title="Orders" description="View and update order status, payment status, and manual activation." /><div className="mt-8"><AdminSection title="Orders"><AdminTable rows={orders} emptyLabel="No orders found." columns={[{ header: "Order", cell: (row) => <div><p className="font-bold text-white">{row.order_number ?? row.id}</p><p>{firstAdminRelation(row.profiles)?.email ?? row.user_id ?? "Guest"}</p><p>{firstAdminRelation(row.products)?.title ?? row.item_type ?? "Item"}</p></div> }, { header: "Access", cell: (row) => <div className="grid gap-1"><span>{formatAccessType(row.access_type)}</span><StatusBadge value={row.activation_status} /></div> }, { header: "Status", cell: (row) => <StatusBadge value={row.status} /> }, { header: "Payment", cell: (row) => <StatusBadge value={row.payment_status} /> }, { header: "Total", cell: (row) => formatBdt(row.total_bdt) }, { header: "Update", cell: (row) => <form action={updateOrderAccessAction} className="grid min-w-52 gap-2"><HiddenId id={row.id} /><Select label="Order" name="status" options={["pending", "paid", "failed", "cancelled"]} /><Select label="Payment" name="paymentStatus" options={["pending", "paid", "failed", "cancelled"]} /><Select label="Activation" name="activationStatus" options={["pending", "active", "cancelled"]} /><ActionButton>Update</ActionButton></form> }]} /></AdminSection></div></div>;
}
