import { grantFreeAccessAction, updateEnrollmentStatusAction } from "@/actions/admin";
import { Button } from "@/components/ui/button";
import { AdminPageHeader, AdminSection, AdminTable, Field, HiddenId, Select, StatusBadge } from "@/components/admin/admin-resource-page";
import { firstAdminRelation, getAdminBatches, getAdminCourses, getAdminEnrollments } from "@/lib/admin-dashboard";

export default async function AdminEnrollmentsPage() {
  const [enrollments, courses, batches] = await Promise.all([getAdminEnrollments(), getAdminCourses(), getAdminBatches()]);
  return <div><AdminPageHeader eyebrow="Access" title="Enrollments" description="Approve enrollments, activate access, and grant free course access." /><div className="mt-8 grid gap-6"><AdminSection title="Grant free access"><form action={grantFreeAccessAction} className="grid gap-4 md:grid-cols-2"><Field label="User ID" name="userId" /><Select label="Course" name="courseId" options={courses.map((course) => ({ label: course.title, value: course.id }))} /><Select label="Batch" name="batchId" required={false} options={[{ label: "No specific batch", value: "" }, ...batches.map((batch) => ({ label: batch.title, value: batch.id }))]} /><div className="flex items-end"><Button type="submit" variant="accent">Grant access</Button></div></form></AdminSection><AdminSection title="Enrollments"><AdminTable rows={enrollments} emptyLabel="No enrollments found." columns={[{ header: "Student", cell: (row) => <div><p className="font-bold text-white">{firstAdminRelation(row.profiles)?.full_name ?? "Student"}</p><p>{firstAdminRelation(row.profiles)?.email ?? row.user_id}</p></div> }, { header: "Course", cell: (row) => firstAdminRelation(row.courses)?.title ?? row.course_id }, { header: "Batch", cell: (row) => firstAdminRelation(row.batches)?.title ?? row.batch_id ?? "-" }, { header: "Status", cell: (row) => <StatusBadge value={row.status} /> }, { header: "Action", cell: (row) => <form action={updateEnrollmentStatusAction} className="grid gap-2"><HiddenId id={row.id} /><Select label="Status" name="status" options={["pending", "active", "cancelled", "completed", "expired"]} /><Button type="submit" size="sm" variant="accent">Update</Button></form> }]} /></AdminSection></div></div>;
}
